

# https://hub.docker.com/_/openjdk
FROM openjdk:11
#LABEL administrator="kyle10_dev@outlook.fr"
EXPOSE 8085:8085
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} mediscreen-patient.jar
ENTRYPOINT ["java","-jar","/mediscreen-patient.jar"]


# https://mkyong.com/docker/docker-and-java-application-examples/
# https://spring.io/guides/topicals/spring-boot-docker/